config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end
  
  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_votable
  belongs_to :user
  validates :title, :description, presence: true

  has_attached_file :image, styles: { medium: "400x400>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @pin = current_user.pins.build
  end

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Successfully updated the Pin!"
    else
      render :edit
    end
  end

  def destroy
    if @pin.destroy
      redirect_to root_path, notice: "Successfully deleted one Pin!"
    end
  end

  def upvote 
    @pin.upvote_by current_user
    redirect_to @pin
  end

  private
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin 
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <h3><%= link_to "Pin Board", root_path, class: "text-danger display-1 font-italic" %></h3>
        </div>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "New Pin", new_pin_path %></li>
            <li><%= link_to "Account", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          </ul>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <% flash.each do|name, msg| %>
        <%= content_tag :div, msg, class: "text-center text-success alert aler-info" %>
      <% end %>

      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: {multipart: true} do |form| %>
  <% if @pin.errors.any? %>
    <h2><%= pluralize(@pin.errors.count, "error") %> prevented from saving! </h2>  

    <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  <% end %>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, placeholder: :image, class: 'form-control-file' %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: :title,class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, placeholder: :description, class: 'form-control form-control-lg' %>
  </div>

  <%= form.submit class: 'btn btn-default btn-primary' %>
<% end %>

app/views/pins/edit.html.erb
<div id="pin_show" class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Pin</h1>
      </div>

      <div class="panel-body pin_image">
        <%= image_tag @pin.image.url(:medium) %>
        <p class="text-warning">Current image!</p>
        <%= render "form" %>
        <%= link_to "Cancel", @pin, class: "btn" %>
      </div>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <div class="text-center">
        <%= link_to (image_tag pin.image.url(:medium)),pin %>
      </div>
      <div class="panel-body">
        <h2><%=link_to pin.title, pin %></h2>
      </div>
      <div class=" text-right">
        <small class="text-warning">Submited on : <%= pin.created_at.strftime("%dth %B %y") %></small>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="text-center">Create Pin</h1>
      </div>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div id="pin_show" class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading pin_image text-center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <h2 class="text-center"><%= @pin.title %></h2>
        <p class="description"><%= @pin.description %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <small class="user"> Submitted by : <span class="text-success"><%= @pin.user.email %> </span></small>
            <br/>
            <small class="text-danger"><%= @pin.created_at.strftime("%H:%M UTC, %dth %B %Y") %></small>
          </div>
            
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default"  do %>
                <span class="glyphicon glyphicon-heart">
                  <%= @pin.get_upvotes.size %>
                </span>
              <% end %>

              <% if user_signed_in? %>
                <%= link_to "Edit", edit_pin_path, class: "btn btn-default text-success" %>
                <%= link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default text-danger" %>

              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>